org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
org.gradle.warning.mode=all
android.lintOptions.abortOnError=false
android.javaCompile.suppressSourceTargetDeprecationWarning=true
android.aaptOptions.cruncherEnabled=false
android.experimental.skipAndLogResourceValidation=true
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
